from typing import Optional
import re
import time
import openai
from openai import OpenAI

from app.integrations.base_assistant import BaseAssistant


class ChatGPTAssistant(BaseAssistant):
    @property
    def name(self) -> str:
        return "ChatGPT"

    @property
    def provider(self) -> str:
        return "OpenAI"

    def __init__(self, api_key: str, model_version: str = "gpt-4o-mini"):
        super().__init__(api_key, model_version)
        self._client = OpenAI(api_key=self._api_key)

    def generate_code(
        self,
        prompt: str,
        language: str = "python",
        context: Optional[str] = None,
    ) -> dict:
        if not prompt or not prompt.strip():
            raise ValueError("prompt must not be empty.")

        instructions = (
            f"You are a coding assistant. Generate correct {language} code. "
            "Return ONLY code. Do not include markdown fences or explanations."
        )

        user_input = prompt.strip()
        if context:
            user_input = f"Context:\n{context.strip()}\n\nTask:\n{user_input}"

        try:
            start = time.perf_counter()

            response = self._client.responses.create(
                model=self.model_version,
                instructions=instructions,
                input=user_input,
            )

            latency_ms = (time.perf_counter() - start) * 1000
            code_text = self._clean_code(response.output_text or "")

            return self._base_response(
                language=language,
                code=code_text,
                explanation="Generated by OpenAI.",
                tokens_used=None,
                latency_ms=round(latency_ms, 2),
            )

        except Exception as e:
            return self.handle_error(e)

    def handle_error(self, raw_error: Exception | dict) -> dict:
        if isinstance(raw_error, dict):
            return self._base_error(
                error_type=raw_error.get("error_type", "UnknownError"),
                message=raw_error.get("message", "An unknown error occurred."),
                retryable=raw_error.get("retryable", False),
            )

        if isinstance(raw_error, openai.AuthenticationError):
            return self._base_error("AuthenticationError", "Invalid OpenAI API key.", False)

        if isinstance(raw_error, openai.RateLimitError):
            return self._base_error("RateLimitError", "OpenAI rate limit exceeded.", True)

        if isinstance(raw_error, openai.APIConnectionError):
            return self._base_error("ConnectionError", "Could not connect to OpenAI.", True)

        if isinstance(raw_error, openai.APIStatusError):
            return self._base_error("APIStatusError", str(raw_error), False)

        return self._base_error(type(raw_error).__name__, str(raw_error), False)

    def _clean_code(self, text: str) -> str:
        text = text.strip()

        fenced = re.search(
            r"```(?:python|javascript|js|php|java|cpp|c\+\+)?\s*(.*?)```",
            text,
            re.DOTALL | re.IGNORECASE,
        )

        if fenced:
            return fenced.group(1).strip()

        return text