import time
import re
from typing import Optional

import openai
from openai import OpenAI

from app.integrations.base_assistant import BaseAssistant


class CoPilotAssistant(BaseAssistant):
    def __init__(self, api_key: str, model_version: str = "gpt-4o"):
        super().__init__(api_key, model_version)
        self._client = OpenAI(api_key=api_key)

    @property
    def name(self) -> str:
        return "GitHub Copilot"

    @property
    def provider(self) -> str:
        return "GitHub / OpenAI"

    def generate_code(
        self,
        prompt: str,
        language: str = "python",
        context: Optional[str] = None,
    ) -> dict:
        system_prompt = (
            f"You are simulating GitHub Copilot for a coding assistant comparison. "
            f"Generate correct {language} code. "
            "Return ONLY code. Do not include markdown fences or explanations."
        )

        user_message = f"{context}\n\n{prompt}" if context else prompt

        try:
            start = time.perf_counter()

            response = self._client.chat.completions.create(
                model=self.model_version,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_message},
                ],
                temperature=0.2,
            )

            latency_ms = (time.perf_counter() - start) * 1000

            content = response.choices[0].message.content or ""
            code = self._clean_code(content)

            return self._base_response(
                language=language,
                code=code,
                explanation="Generated by Copilot integration.",
                tokens_used=response.usage.total_tokens if response.usage else None,
                latency_ms=round(latency_ms, 2),
            )

        except Exception as e:
            return self.handle_error(e)

    def handle_error(self, raw_error: Exception | dict) -> dict:
        error_map = {
            openai.AuthenticationError: ("auth_error", False),
            openai.RateLimitError: ("rate_limit", True),
            openai.BadRequestError: ("invalid_request", False),
            openai.APIConnectionError: ("network_error", True),
        }

        for exc_type, (error_type, retryable) in error_map.items():
            if isinstance(raw_error, exc_type):
                return self._base_error(error_type, str(raw_error), retryable)

        return self._base_error(type(raw_error).__name__, str(raw_error), retryable=False)

    def _clean_code(self, text: str) -> str:
        text = text.strip()

        fenced = re.search(
            r"```(?:python|javascript|js|php|java|cpp|c\+\+)?\s*(.*?)```",
            text,
            re.DOTALL | re.IGNORECASE,
        )

        if fenced:
            return fenced.group(1).strip()

        return text