import time
import re
from typing import Optional

import google.generativeai as genai
from google.api_core import exceptions

from app.integrations.base_assistant import BaseAssistant


class GeminiAssistant(BaseAssistant):
    def __init__(self, api_key: str, model_version: str = "gemini-1.5-pro"):
        super().__init__(api_key, model_version)
        genai.configure(api_key=self._api_key)
        self._model = genai.GenerativeModel(model_version)

    @property
    def name(self) -> str:
        return "Google Gemini"

    @property
    def provider(self) -> str:
        return "Google"

    def generate_code(
        self,
        prompt: str,
        language: str = "python",
        context: Optional[str] = None,
    ) -> dict:
        system_prompt = (
            f"You are an expert {language} developer. "
            "Return ONLY code. Do not include markdown fences or explanations."
        )

        user_message = f"{context}\n\n{prompt}" if context else prompt

        try:
            start_time = time.perf_counter()

            response = self._model.generate_content(f"{system_prompt}\n\n{user_message}")

            latency_ms = (time.perf_counter() - start_time) * 1000
            content = response.text or ""
            code = self._clean_code(content)

            tokens = None
            if getattr(response, "usage_metadata", None):
                tokens = getattr(response.usage_metadata, "total_token_count", None)

            return self._base_response(
                language=language,
                code=code,
                explanation="Generated by Gemini.",
                tokens_used=tokens,
                latency_ms=round(latency_ms, 2),
            )

        except Exception as e:
            return self.handle_error(e)

    def handle_error(self, raw_error: Exception | dict) -> dict:
        if isinstance(raw_error, exceptions.Unauthenticated):
            return self._base_error("auth_error", "Invalid Gemini API key.", retryable=False)

        if isinstance(raw_error, exceptions.ResourceExhausted):
            return self._base_error("rate_limit", "Gemini quota exceeded.", retryable=True)

        if isinstance(raw_error, exceptions.InvalidArgument):
            return self._base_error("invalid_request", str(raw_error), retryable=False)

        return self._base_error(type(raw_error).__name__, str(raw_error), retryable=False)

    def _clean_code(self, text: str) -> str:
        text = text.strip()

        fenced = re.search(
            r"```(?:python|javascript|js|php|java|cpp|c\+\+)?\s*(.*?)```",
            text,
            re.DOTALL | re.IGNORECASE,
        )

        if fenced:
            return fenced.group(1).strip()

        return text