from typing import Optional
import openai
from openai import OpenAI

from base_assistant import BaseAssistant


class ChatGPTAssistant(BaseAssistant):
    # Returns the name of the assistant
    @property
    def name(self) -> str:
        return "ChatGPT"

    # Returns the company/provider behind the assistant
    @property
    def provider(self) -> str:
        return "OpenAI"

    # Sets up the assistant by calling the base class constructor
    # and creating an OpenAI client for API requests
    def __init__(self, api_key: str, model_version: str = "gpt-5.4"):
        super().__init__(api_key, model_version)
        self._client = OpenAI(api_key=self._api_key)

    # Generates code from a user prompt using the OpenAI model
    def generate_code(
        self,
        prompt: str,
        language: str = "python",
        context: Optional[str] = None,
    ) -> dict:
        # Prevents sending an empty prompt to the API
        if not prompt or not prompt.strip():
            raise ValueError("prompt must not be empty.")

        # Tells the model how it should format and approach the response
        instructions = (
            f"You are a coding assistant. Generate clear, correct {language} code. "
            "Return the code and a short explanation."
        )

        # Starts with the user's main coding request
        user_input = prompt.strip()

        # Adds extra context if the caller provided it
        if context:
            user_input = f"Context:\n{context.strip()}\n\nTask:\n{user_input}"

        # Tries to send the request to OpenAI and return a formatted response
        try:
            response = self._client.responses.create(
                model=self.model_version,
                instructions=instructions,
                input=user_input,
            )

            # Gets the generated text returned by the model
            code_text = response.output_text.strip()

            # Returns the result in the standard response format used by the project
            return self._base_response(
                language=language,
                code=code_text,
                explanation="Generated by OpenAI.",
            )

        except Exception as e:
            return self.handle_error(e)

    # Converts OpenAI-specific errors into the standard project error format
    def handle_error(self, raw_error: Exception | dict) -> dict:
        # If the error is already in dictionary form, convert it directly
        if isinstance(raw_error, dict):
            return self._base_error(
                error_type=raw_error.get("error_type", "UnknownError"),
                message=raw_error.get("message", "An unknown error occurred."),
                retryable=raw_error.get("retryable", False),
            )

        # Handles invalid API key or failed authentication
        if isinstance(raw_error, openai.AuthenticationError):
            return self._base_error(
                error_type="AuthenticationError",
                message="Invalid OpenAI API key or authentication failed.",
                retryable=False,
            )

        # Handles rate limit errors when too many requests are sent
        if isinstance(raw_error, openai.RateLimitError):
            return self._base_error(
                error_type="RateLimitError",
                message="Rate limit exceeded. Please try again later.",
                retryable=True,
            )

        # Handles connection-related issues
        if isinstance(raw_error, openai.APIConnectionError):
            return self._base_error(
                error_type="ConnectionError",
                message="Could not connect to the OpenAI API.",
                retryable=True,
            )

        # Handles other API status errors
        if isinstance(raw_error, openai.APIStatusError):
            return self._base_error(
                error_type="APIStatusError",
                message=str(raw_error),
                retryable=False,
            )

        # Fallback for regular Python/OpenAI exceptions
        return self._base_error(
            error_type=type(raw_error).__name__,
            message=str(raw_error),
            retryable=False,
        )