from typing import Optional
import time

import requests

from app.base_assistant import BaseAssistant


class GrokAssistant(BaseAssistant):
    @property
    def name(self) -> str:
        return "Grok"

    @property
    def provider(self) -> str:
        return "xAI"

    def generate_code(
        self,
        prompt: str,
        language: str = "python",
        context: Optional[str] = None,
    ) -> dict:
        url = "https://api.x.ai/v1/chat/completions"
        full_prompt = f"Write {language} code:\n{prompt}"

        if context:
            full_prompt += f"\n\nContext:\n{context}"

        payload = {
            "model": self.model_version or "grok-1",
            "messages": [{"role": "user", "content": full_prompt}],
        }
        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json",
        }

        start = time.perf_counter()

        try:
            response = requests.post(
                url,
                headers=headers,
                json=payload,
                timeout=30,
            )
            response.raise_for_status()
            data = response.json()

            content = data["choices"][0]["message"]["content"]
            latency_ms = (time.perf_counter() - start) * 1000

            return self._base_response(
                language=language,
                code=content,
                explanation="Generated by Grok",
                tokens_used=data.get("usage", {}).get("total_tokens"),
                latency_ms=latency_ms,
            )
        except Exception as raw_error:
            return self.handle_error(raw_error)

    def handle_error(self, raw_error: Exception | dict) -> dict:
        retryable = isinstance(
            raw_error,
            (
                requests.exceptions.Timeout,
                requests.exceptions.ConnectionError,
                requests.exceptions.HTTPError,
            ),
        )

        if isinstance(raw_error, dict):
            error_type = raw_error.get("error_type", "ProviderError")
            message = raw_error.get("message", "Unknown Grok error")
            retryable = raw_error.get("retryable", retryable)
        else:
            error_type = type(raw_error).__name__
            message = str(raw_error)

        return self._base_error(
            error_type=error_type,
            message=message,
            retryable=retryable,
        )
