from base_assistant import BaseAssistant
import requests
import time


class GrokAssistant(BaseAssistant):

    @property
    def name(self) -> str:
        return "Grok"

    @property
    def provider(self) -> str:
        return "xAI"
    
def generate_code(self, prompt, language="python", context=None):
    url = "https://api.x.ai/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {self._api_key}",
        "Content-Type": "application/json"
    }

    full_prompt = f"Write {language} code:\n{prompt}"
    if context:
        full_prompt += f"\nContext:\n{context}"

    payload = {
        "model": self.model_version or "grok-1",
        "messages": [
            {"role": "user", "content": full_prompt}
        ]
    }

    start = time.time()

    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        data = response.json()

        content = data["choices"][0]["message"]["content"]

        latency = (time.time() - start) * 1000

        return self._base_response(
            language=language,
            code=content,
            explanation="Generated by Grok",
            tokens_used=data.get("usage", {}).get("total_tokens"),
            latency_ms=latency
        )

    except Exception as e:
        return self.handle_error(e)


def handle_error(self, raw_error):
    return self._base_error(
        error_type=type(raw_error).__name__,
        message=str(raw_error),
        retryable=True
    )